name: Docker

on:
  push:
      branches:
        - master # Publish `master` as Docker `latest` image.
        - develop # Publish `master` as Docker `staging` image.
        - feature/security
      # Publish `v1.2.3` tags as releases.
      tags:
        - v*
env:
  IMAGE_NAME: auth-service-tests
  IMAGE_ID: sensateiot/auth-service-tests
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  push-auth-service-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          cd AuthService
          docker build . --tag $IMAGE_NAME
