name: Format check
on:
  push:
    branches: 
      - develop
      - master
      - feature/**
      - release/**
  pull_request:
    branches: 
      - master
      - develop
jobs:
  dotnet-format-api:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"
      - run: |
          dotnet tool install -g dotnet-format
          echo "$HOME/.dotnet/tools" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Run dotnet format
        run: |
          dotnet format --check

  dotnet-format-network:
    runs-on: windows-latest
    env:
      working-directory: ./SensateIoT.Platform/SensateIoT.Platform.Network
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"
      - run: |
          dotnet tool install -g dotnet-format
          echo "$HOME/.dotnet/tools" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Run dotnet format
        working-directory: ${{env.working-directory}}
        run: |
          dotnet format --check
