name: Format check
on:
  push:
    branches: 
      - develop
      - master
      - feature/**
  pull_request:
    branches: 
      - master
      - develop
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: "3.1.100"
      - run:
          dotnet tool install -g dotnet-format

      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-changed-files: "true"
          action: "check"
